internal: Include StatusFunc for Releaser plugins
hashicorp/waypoint-plugin-sdk pull request #32
Opened 2021-05-26 20:11 UTC by briancain

This pull request includes the StatusFunc for Releaser so that Releaser components can invoke the StatusFunc.

This pull request also fixes a protoc bug where import paths were bad. The error in question:

```
protoc-gen-go: invalid Go import path "." for "plugin.proto"

The import path must contain at least one forward slash ('/') character.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
```

I was running into this error in https://github.com/hashicorp/waypoint-plugin-sdk/pull/20 so I imagine this fix should resolve that PR.

2021-05-26 20:13 UTC, evanphx requested changes

2021-05-26 20:13 UTC, evanphx commented on proto/unused.proto
> +option go_package = "./;proto";
My only worry is if older protobuf-gen-go won't treat this the same, I saw that previously. We might need to separate your fix from these protobuf semantic changes.

2021-05-26 20:16 UTC, izaaklauer commented on go.sum
> +google.golang.org/protobuf v1.26.0-rc.1/go.mod h1:jlhhOSvTdKEhbULTjvd4ARK9grFBp09yW+WbY/TyQbw=
`v1.26.0-rc.1` - is this moving us closer to the bleeding edge of protobuf than we want to be?

2021-05-27 16:32 UTC, mitchellh approved these changes

2021-05-27 16:43 UTC, merged